### ISSUE TITLE
post scores

### ISSUE THREAD

**Issue by interludic** [dolejska-daniel/challonge-api#2]
All the readme.md says is to list a tournament, what about extending so we can post scores and show game status, live updates and a leader board?

or am i missing something aand this is what we can do?

**Comment by dolejska-daniel** [comment]
You have closed the issue but I am going to reply anyway:

**Yes** - the things you have mentioned are already implemented. They are just not documented yet. Check out the [main library file](https://github.com/dolejska-daniel/challonge-api/blob/master/src/ChallongeAPI/ChallongeAPI.php) to learn more about these functions.

I am planning on continuing on working on this library, documenting, extending it's functionality, but currently I am too busy with my [League of Legends Riot API](https://github.com/dolejska-daniel/riot-api) and I am also on vacation right now :D

Have a nice day :)
