### ISSUE TITLE
Limited matches

### ISSUE THREAD

**Issue by interludic** [dolejska-daniel/challonge-api#3]
Why is there only 15 matches shown here?
https://challonge.com/3x3CompSummer2020GroupA.svg

I cannot see any obvious limits here:
https://api.challonge.com/v1/documents/matches/index#

There should be 28 matches in groupA 
https://challonge.com/3x3CompAutumn2020GroupA/groups

...and a further 3 in the finals

Am i missing something?

**Comment by dolejska-daniel** [comment]
https://challonge.com/3x3CompAutumn2020GroupA/groups.svg should be used instead. Image you've sent is for `3x3CompSummer2020GroupA`, but the tournament page you've sent is for `3x3CompAutumn2020GroupA`.

**Comment by interludic** [comment]
Thanks for the quick response.

What I meant is that the matches endpoint only lists 15 matches, and I
found the svg did the same thing coincidentally.

So I am actually talking about the API response.

**Comment by dolejska-daniel** [comment]
What do you mean? Those are two different tournaments... 😕

**Comment by interludic** [comment]
You are correct, my apologies.

well done on a great service.

**Comment by interludic** [comment]
Where is the best place to find out future developments for this project/api/challonge?
